module.exports = {
	environment: process.env.ENVIRONMENT,
	app: {
		name: process.env.APP_NAME,
		url: process.env.APP_URL,
		domain: process.env.APP_DOMAIN,
		port: process.env.APP_PORT,
	},
	db: {
		host: process.env.DB_HOST,
		name: process.env.DB_NAME,
		port: process.env.DB_PORT,
	},
	session: {
		name: process.env.SESSION_NAME,
		key: process.env.SESSION_KEY,
	},
	frontAppUrl: process.env.FRONT_APP_URL,
	saltRounds: process.env.SALT_ROUNDS,
	authServiceProviders: {
		google: {
			clientId: process.env.GOOGLE_CLIENT_ID,
			clientSecret: process.env.GOOGLE_CLIENT_SECRET,
			callbackUrl: process.env.GOOGLE_CALLBACK_URL,
		},
		twitter: {
			consumerKey: process.env.TWITTER_CONSUMER_KEY,
			consumerSecret: process.env.TWITTER_CONSUMER_SECRET,
			callbackUrl: process.env.TWITTER_CALLBACK_URL,
		},
		facebook: {
			clientId: process.env.FACEBOOK_CLIENT_ID,
			clientSecret: process.env.FACEBOOK_CLIENT_SECRET,
			callbackUrl: process.env.FACEBOOK_CALLBACK_URL,
			successRedirectUrl: process.env.FACEBOOK_SUCCESS_REDIRECT_URL,
		},
		apple: {},
		successRedirectUrl: process.env.SOCIAL_SUCCESS_REDIRECT_URL,
	},
	defaultLanguage: process.env.DEFAULT_LANGUAGE,
	defaultCurrency: process.env.DEFAULT_CURRENCY,
	anonymousNameLength: process.env.ANONYMOUS_NAME_LENGTH,
	gameNextStepDelay: process.env.GAME_NEXT_STEP_DELAY_MS,
	renewAccountsToken: process.env.RENEW_ACCOUNTS_TOKEN,
	email: {
		host: process.env.EMAIL_HOST,
		port: process.env.EMAIL_PORT,
		secure: process.env.EMAIL_SECURE,
		auth: {
			user: process.env.EMAIL_USERNAME,
			pass: process.env.EMAIL_PASSWORD,
		},
		tls: {
			rejectUnauthorized: process.env.EMAIL_TLS_REJECT_UNAUTHORIZED,
			// servername: process.env.EMAIL_TLS_SERVER_NAME,
		},
	},
	emailFrom: process.env.EMAIL_FROM,
	plivoId: process.env.PLIVO_ID,
	plivoAuthToken: process.env.PLIVO_AUTH_TOKEN,
	plivoSender: process.env.PLIVO_SENDER,
	openAIApiKey: process.env.OPENAI_API_KEY,
	paypalClientId: process.env.PAYPAL_CLIENT_ID,
	paypalClientSecret: process.env.PAYPAL_CLIENT_SECRET,
};
