const mongoose = require("mongoose");
const { Schema } = mongoose;

const userSchema = new Schema({
	firstName: String,
	lastName: String,
	anonymousName: String,
	email: String,
	mobile: String,
	emailVerified: Boolean,
	mobileVerified: Boolean,
	password: String,
	loginProvider: String,
	providerId: String,
	isActive: Boolean,
	userType: String,
	hasCompletedSignup: Boolean,
	created_at: Date,
	referCode: String,
	referer: Object,
	inWaitList: Boolean,
	gender: Object,
	education: Object,
	country: String,
	city: String,
	furtherQuestions: Array,
	preferedCategories: Array,
	accountType: Object,
	preferedLanguage: Object,
	preferedFont: String,
	preferedCharity: Object,
	defaultHomePage: String,
	profilePicture: String,
	assets: Object,
	maxInvites: Number,
	invitations: Array,
	accessTokens: Array,
	statistics: Object,
	games: Object,
	hasSeenIntros: {
		dashboard: Boolean,
		games: Boolean,
		triviaHub: Boolean,
		shop: Boolean,
	},
	socketId: String,
});

module.exports = mongoose.model("User", userSchema);
